rule: |
  &a&lマイクラ鯖共通ルール
  &f・道のど真ん中に建築はしないでください。
  &f・荒らし・チート・ハッキングなどは禁止します。
  &f・ハッククライアントは使用しないでください。
  &f・人の家(敷地)に勝手に入らないでください
  &f・人を &n'わざと'&f 倒し、アイテムを略奪をすることを禁止します。
  &f・&c&lOPの指示に従ってください。
  &f・&cVPN/プロキシを&n経由&cしてアクセスしないでください


menu:
  buttons:
    server_selector: true
    last_spawn: true
    ender_chest: true
    player_head: true
    first_spawn: true

    trash_box: true

# ========================= #
#       寄付者向けの機能       #
# ========================= #
donate:
  fly: false